version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: devmastery-db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: devmastery
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 